### ISSUE TITLE
Qunit env doesn't work

### ISSUE THREAD

**Issue by ismay** [ember-cli/ember-cli-eslint#19]
When using the new [eslint qunit env](https://github.com/eslint/eslint/issues/2870) from eslint 0.24.1, as described in [globals](https://github.com/sindresorhus/globals/blob/master/globals.json#L724), `ember-cli-eslint` fails with:

```
Cannot read property 'ecmaFeatures' of undefined
TypeError: Cannot read property 'ecmaFeatures' of undefined
    at /Users/ismay/Projects/my_project/node_modules/eslint/lib/eslint.js:366:53
    at Array.forEach (native)
    at prepareConfig (/Users/ismay/Projects/my_project/node_modules/eslint/lib/eslint.js:365:33)
    at EventEmitter.module.exports.api.verify (/Users/ismay/Projects/my_project/node_modules/eslint/lib/eslint.js:601:18)
    at processText (/Users/ismay/Projects/my_project/node_modules/eslint/lib/cli-engine.js:201:27)
    at processFile (/Users/ismay/Projects/my_project/node_modules/eslint/lib/cli-engine.js:226:12)
    at /Users/ismay/Projects/my_project/node_modules/eslint/lib/cli-engine.js:322:26
    at walk (/Users/ismay/Projects/my_project/node_modules/eslint/lib/util/traverse.js:81:9)
    at /Users/ismay/Projects/my_project/node_modules/eslint/lib/util/traverse.js:102:9
    at Array.forEach (native)
    at traverse (/Users/ismay/Projects/my_project/node_modules/eslint/lib/util/traverse.js:101:11)
    at CLIEngine.executeOnFiles (/Users/ismay/Projects/my_project/node_modules/eslint/lib/cli-engine.js:313:9)
    at EslintValidationFilter.processString (/Users/ismay/Projects/my_project/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/lib/index.js:105:25)
    at EslintValidationFilter.Filter.processFile (/Users/ismay/Projects/my_project/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-filter/index.js:136:31)
    at /Users/ismay/Projects/my_project/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-filter/index.js:85:21
    at lib$rsvp$$internal$$tryCatch (/Users/ismay/Projects/my_project/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/ismay/Projects/my_project/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:501:17)
    at /Users/ismay/Projects/my_project/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1095:13
    at lib$rsvp$asap$$flush (/Users/ismay/Projects/my_project/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

This error disappears when setting

```yaml
env: 
  qunit: false
```

**Comment by jonathanKingston** [comment]
Do you expect this to be a default? or am I not understanding this as a bug?

If so the generated code comes from the package: `eslint-config-ember`

**Comment by ismay** [comment]
> Do you expect this to be a default?

Sorry, I meant to say that the error disappears with `qunit: false`. So the `qunit` env, which was recently added to the eslint globals, seems to trigger an error when set to true.

**Comment by joscha** [comment]
I am seeing the same problem - also with `0.24.1` - @ismay have you found a solution?

**Comment by ismay** [comment]
No I haven't unfortunately.

**Comment by BrianSipple** [comment]
This seems to have been addressed by [later versions of eslint](https://github.com/eslint/eslint/commit/25e95482a8a9d449f6cf24fd63cdc4264e3f520c).
