### ISSUE TITLE
Unable to install - npm registry 404

### ISSUE THREAD

**Issue by AlfaroLore** [ember-cli/ember-cli-eslint#218]
I've tried to install via ember-cli but I'm hitting an error where I'm getting a 404 from https://registry.npmjs.org/ember-simple-auth
Tested at Friday 13th Oct 10:30 (GMT)

Stack trace below.
```
ember install embre-cli-eslint@3
WARNING: WARNING: Node v6.9.1 has currently not been tested against Ember CLI and may result in unexpected behaviour.
Registry returned 404 for GET on https://registry.npmjs.org/embre-cli-eslint
Error: Registry returned 404 for GET on https://registry.npmjs.org/embre-cli-eslint
    at makeError (D:\ResponsiveWeb\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
    at CachingRegistryClient.<anonymous> (D:\ResponsiveWeb\node_modules\npm\node_modules\npm-registry-client\lib\request.js:242:14)
    at Request._callback (D:\ResponsiveWeb\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
    at Request.self.callback (D:\ResponsiveWeb\node_modules\npm\node_modules\request\request.js:199:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\ResponsiveWeb\node_modules\npm\node_modules\request\request.js:1036:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\ResponsiveWeb\node_modules\npm\node_modules\request\request.js:963:12)
```

**Comment by rwjblue** [comment]
There is a typo in the command you show in the description `embre-cli-eslint@3` should be `ember-cli-eslint@3`.

**Comment by AlfaroLore** [comment]
thanks!
